In [87]:
import sys
sys.executable

'C:\\Users\\user\\anaconda3\\python.exe'

In [88]:
import numpy as np
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.sql import text
from urllib.request import urlopen, urlretrieve
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import warnings
import time
warnings.filterwarnings('ignore')

In [89]:
driver = webdriver.Chrome()
url = "https://www.etnews.com/news/section.html?id1=02"
driver.get(url)

In [90]:
elem = driver.find_element(By.CLASS_NAME,"article_body")

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".article_body"}
  (Session info: chrome=123.0.6312.123); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF7A1137032+63090]
	(No symbol) [0x00007FF7A10A2C82]
	(No symbol) [0x00007FF7A0F3EC65]
	(No symbol) [0x00007FF7A0F8499D]
	(No symbol) [0x00007FF7A0F84ADC]
	(No symbol) [0x00007FF7A0FC5B37]
	(No symbol) [0x00007FF7A0FA701F]
	(No symbol) [0x00007FF7A0FC3412]
	(No symbol) [0x00007FF7A0FA6D83]
	(No symbol) [0x00007FF7A0F783A8]
	(No symbol) [0x00007FF7A0F79441]
	GetHandleVerifier [0x00007FF7A15325AD+4238317]
	GetHandleVerifier [0x00007FF7A156F70D+4488525]
	GetHandleVerifier [0x00007FF7A15679EF+4456495]
	GetHandleVerifier [0x00007FF7A1210576+953270]
	(No symbol) [0x00007FF7A10AE54F]
	(No symbol) [0x00007FF7A10A9224]
	(No symbol) [0x00007FF7A10A935B]
	(No symbol) [0x00007FF7A1099B94]
	BaseThreadInitThunk [0x00007FFBCF5D257D+29]
	RtlUserThreadStart [0x00007FFBD0AEAA48+40]

In [ ]:
elem = driver.find_element(By.TAG_NAME,"h2")

In [ ]:
for i in range(5):
    time.sleep(1)
    driver.find_element(By.CLASS_NAME,"paginate").find_elements(By.TAG_NAME,'a')[i+1].click() [i-1].click()

In [405]:
elem.find_elements(By.TAG_NAME,'a')

AttributeError: 'list' object has no attribute 'find_elements'

In [401]:
bs = BeautifulSoup(driver.page_source, 'html.parser')
bs.title.text

'韓 AI·디지털 혁신, WIS 타고 글로벌로 향한다 - 전자신문'

In [82]:
url = "https://www.etnews.com/news/section.html?id1=02&page=9"
driver = webdriver.Chrome()
driver.get(url)

In [84]:

desired_page = 7
current_page = 9

# 반복문을 통해 원하는 페이지까지 이동합니다.
while current_page != desired_page:
    # 현재 페이지 번호 요소를 찾습니다.
    current_page_element = driver.find_element(By.CSS_SELECTOR, 'CSS 선택자: 현재 페이지 번호를 나타내는 요소')
    current_page = int(current_page_element.text)

    # 원하는 페이지에 도달했는지 확인합니다.
    if current_page == desired_page:
        break

    # 다음 페이지로 이동하는 요소를 찾아 클릭합니다.
    next_page_element = driver.find_element(By.CSS_SELECTOR, 'CSS 선택자: 다음 페이지로 이동하는 요소')
    next_page_element.click()

    # 페이지 로드 대기
    time.sleep(1)

# 원하는 페이지에 도달한 후 작업을 수행합니다.
# main_news_img 클래스를 가진 요소를 찾습니다.
elem = driver.find_element(By.CLASS_NAME, "main_news_img")

# main_news_img 요소 내에서 태그 이름이 "a"인 요소를 찾습니다.
news_elem = elem.find_elements(By.TAG_NAME, "a")

# 첫 번째 "a" 요소를 클릭합니다.
news_elem[0].click()

# 이전 페이지로 돌아갑니다.
driver.execute_script("window.history.go(-1)")

# 브라우저 종료
driver.quit()

JavascriptException: Message: javascript error: {"status":32,"value":"An invalid or illegal selector was specified"}
  (Session info: chrome=123.0.6312.123)
Stacktrace:
	GetHandleVerifier [0x00007FF7A1137032+63090]
	(No symbol) [0x00007FF7A10A2C82]
	(No symbol) [0x00007FF7A0F3EC65]
	(No symbol) [0x00007FF7A0F43D21]
	(No symbol) [0x00007FF7A0F46159]
	(No symbol) [0x00007FF7A0F46200]
	(No symbol) [0x00007FF7A0F8460C]
	(No symbol) [0x00007FF7A0F84ADC]
	(No symbol) [0x00007FF7A0FC5B37]
	(No symbol) [0x00007FF7A0FA701F]
	(No symbol) [0x00007FF7A0FC3412]
	(No symbol) [0x00007FF7A0FA6D83]
	(No symbol) [0x00007FF7A0F783A8]
	(No symbol) [0x00007FF7A0F79441]
	GetHandleVerifier [0x00007FF7A15325AD+4238317]
	GetHandleVerifier [0x00007FF7A156F70D+4488525]
	GetHandleVerifier [0x00007FF7A15679EF+4456495]
	GetHandleVerifier [0x00007FF7A1210576+953270]
	(No symbol) [0x00007FF7A10AE54F]
	(No symbol) [0x00007FF7A10A9224]
	(No symbol) [0x00007FF7A10A935B]
	(No symbol) [0x00007FF7A1099B94]
	BaseThreadInitThunk [0x00007FFBCF5D257D+29]
	RtlUserThreadStart [0x00007FFBD0AEAA48+40]

In [86]:
elem = driver.find_elements(By.CLASS_NAME, "main_news_img")
num = len(elem)
for i in range(num):
    elem = driver.find_elements(By.CLASS_NAME, "main_news_img")
    news_elem = elem[i].find_elements(By.TAG_NAME, "a")
    news_elem[0].click()
    print(driver.find_element(By.TAG_NAME,"h2").text)
    time.sleep(2)
    driver.execute_script("window.history.go(-1)")


    desired_page = 7

# 현재 페이지 번호를 나타내는 변수 (초기값을 0으로 설정)
    current_page = 0
    for i <= 7 
    elem = driver.find_element(By.CLASS_NAME, "main_news_img")
        break
    try

SyntaxError: invalid syntax (3417983471.py, line 16)

In [73]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time

# 브라우저 드라이버 초기화
driver = webdriver.Chrome()  # Chrome 브라우저를 사용합니다.

# 원하는 URL로 이동
url = 'https://www.etnews.com/news/section.html?id1=02&page=3'
driver.get(url)

# 원하는 페이지 번호
desired_page = 7

# 현재 페이지 번호를 나타내는 변수 (초기값을 0으로 설정)
current_page = 3

# 반복문을 통해 원하는 페이지까지 이동합니다.
while current_page != desired_page:
    # 현재 페이지 번호 요소를 찾습니다.
    current_page_element = driver.find_element(By.CSS_SELECTOR, 'a')
    current_page = int(current_page_element.text)

    # 원하는 페이지에 도달했는지 확인합니다.
    if current_page == desired_page:
        break

    # 다음 페이지로 이동하는 요소를 찾아 클릭합니다.
    next_page_element = driver.find_element(By.CSS_SELECTOR, 'a')
    next_page_element.click()

    # 페이지 로드 대기
    time.sleep(1)

# 원하는 페이지에 도달한 후 작업을 수행합니다.
# main_news_img 클래스를 가진 요소를 찾습니다.
elem = driver.find_element(By.CLASS_NAME, "main_news_img")

# main_news_img 요소 내에서 태그 이름이 "a"인 요소를 찾습니다.
news_elem = elem.find_elements(By.TAG_NAME, " article:nth-child(1) ")

# 첫 번째 "a" 요소를 클릭합니다.
news_elem[0].click()

# 이전 페이지로 돌아갑니다.
driver.execute_script("window.history.go(-1)")

# 브라우저 종료
driver.quit()

ValueError: invalid literal for int() with base 10: ''

In [54]:
news_elem = driver.execute_script("window.history.go(-1)")
news_elem

In [ ]:
if i == 7:
            sql += f",{col}= '{val}', "
        else:
            sql += f",{col}= '{val}' "
        i += 1

In [345]:
len(elem.text)

0

In [305]:
print('a')
time.sleep(1)
print('b')

a
b

In [329]:
driver = webdriver.Chrome()
url = "https://www.google.com/imghp?hl=ko&tab=wi"
driver.get(url)
image ='고양이'
elem = driver.find_element(By.NAME, "q")
elem.send_keys(image)
elem.send_keys(Keys.ENTER)

In [330]:
elem_list = driver.find_elements(By.CLASS_NAME,"mNsIhb")
len(elem_list)
# image list
# elem = driver.find_elements(By.CSS_SELECTOR,""

97

In [334]:
for i,elem in enumerate(elem_list,1):
    time.sleep(1)
    try : 
        time.sleep(2)
        elem.click()
        time.sleep(1)
        src = driver.find_element(By.CLASS_NAME,"sFlh5c.pT0Scc.iPVvYb").get_attribute('src')
        time.sleep(1)
        urlretrieve(src, "./cat/cat" + str(i) + ".jpg")
    except :
        pass

In [301]:
src

'https://i.namu.wiki/i/d1A_wD4kuLHmOOFqJdVlOXVt1TWA9NfNt_HA0CS0Y_N0zayUAX8olMuv7odG2FiDLDQZIRBqbPQwBSArXfEJlQ.webp'

In [308]:
elem[1].click()
src =driver.find_element(By.CLASS_NAME,"sFlh5c.pT0Scc.iPVvYb").get_attribute('src')

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".sFlh5c.pT0Scc.iPVvYb"}
  (Session info: chrome=123.0.6312.123); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF7A1137032+63090]
	(No symbol) [0x00007FF7A10A2C82]
	(No symbol) [0x00007FF7A0F3EC65]
	(No symbol) [0x00007FF7A0F8499D]
	(No symbol) [0x00007FF7A0F84ADC]
	(No symbol) [0x00007FF7A0FC5B37]
	(No symbol) [0x00007FF7A0FA701F]
	(No symbol) [0x00007FF7A0FC3412]
	(No symbol) [0x00007FF7A0FA6D83]
	(No symbol) [0x00007FF7A0F783A8]
	(No symbol) [0x00007FF7A0F79441]
	GetHandleVerifier [0x00007FF7A15325AD+4238317]
	GetHandleVerifier [0x00007FF7A156F70D+4488525]
	GetHandleVerifier [0x00007FF7A15679EF+4456495]
	GetHandleVerifier [0x00007FF7A1210576+953270]
	(No symbol) [0x00007FF7A10AE54F]
	(No symbol) [0x00007FF7A10A9224]
	(No symbol) [0x00007FF7A10A935B]
	(No symbol) [0x00007FF7A1099B94]
	BaseThreadInitThunk [0x00007FFBCF5D257D+29]
	RtlUserThreadStart [0x00007FFBD0AEAA48+40]

In [262]:
# elem = driver.find_elements(By.ID,"dimg_233")

In [258]:
elem[10].click()

In [257]:
# elem = driver.find_elements(By.CLASS_NAME, "tb08Pd")
# elem = driver.find_elements(By.CLASS_NAME,"mNsIhb")
# driver = webdriver.Chrome()

In [ ]:
element driver.find_element(By.id,"#APjFqb")

In [184]:
elem = driver.find_element(By.Name,"q")
#elem = driver.find_element(By.Id,"#APjFqb")

NameError: name 'By' is not defined

In [170]:
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/human")

In [171]:
conn = engine.connect()

In [172]:
stmt = """select * from test"""
pd.read_sql(stmt,conn)

ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'human.test' doesn't exist")
[SQL: select * from test]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [135]:
sql= """
insert into test(a,b)
values('a1','b1')

"""
stmt = text(sql)
conn.execute(stmt)
pd.read_sql("select * from test",conn)

ProgrammingError: (pymysql.err.ProgrammingError) (1146, "Table 'human.test' doesn't exist")
[SQL:
insert into test(a,b)
values('a1','b1')

]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [136]:
sql = """
select * 
  from information_schema.tables 
 where table_schema = 'human'
 
"""
pd.read_sql(sql,conn)

,TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,TABLE_TYPE,ENGINE,VERSION,ROW_FORMAT,TABLE_ROWS,AVG_ROW_LENGTH,DATA_LENGTH,...,AUTO_INCREMENT,CREATE_TIME,UPDATE_TIME,CHECK_TIME,TABLE_COLLATION,CHECKSUM,CREATE_OPTIONS,TABLE_COMMENT,MAX_INDEX_LENGTH,TEMPORARY
0,def,human,고객,BASE TABLE,InnoDB,10,Dynamic,9,1820,16384,...,NaN,2024-03-25 14:43:39,NaT,None,utf8mb4_general_ci,None,,,0,N
1,def,human,제품,BASE TABLE,InnoDB,10,Dynamic,7,2340,16384,...,NaN,2024-03-25 14:43:39,NaT,None,utf8mb4_general_ci,None,,,0,N
2,def,human,주문,BASE TABLE,InnoDB,10,Dynamic,10,1638,16384,...,NaN,2024-03-25 14:43:39,NaT,None,utf8mb4_general_ci,None,,,0,N
3,def,human,accident,BASE TABLE,InnoDB,10,Dynamic,4099,83,344064,...,4120.0,2024-03-26 16:17:35,NaT,None,utf8mb4_general_ci,None,,교통사고사망자,0,N
4,def,human,board,BASE TABLE,InnoDB,10,Dynamic,5,3276,16384,...,NaN,2024-03-27 15:32:13,NaT,None,utf8mb4_general_ci,None,,,0,N
5,def,human,board_code,BASE TABLE,InnoDB,10,Dynamic,4,4096,16384,...,NaN,2024-03-27 15:34:35,NaT,None,utf8mb4_general_ci,None,,,0,N
6,def,human,board_file,BASE TABLE,InnoDB,10,Dynamic,2,8192,16384,...,NaN,2024-03-27 15:41:05,NaT,None,utf8mb4_general_ci,None,,,0,N
7,def,human,countries,BASE TABLE,InnoDB,10,Dynamic,25,655,16384,...,NaN,2024-03-27 16:20:22,NaT,None,utf8mb4_general_ci,None,,country table. Contains 25 rows. References wi...,0,N
8,def,human,departments,BASE TABLE,InnoDB,10,Dynamic,27,606,16384,...,NaN,2024-03-27 16:20:22,NaT,None,utf8mb4_general_ci,None,,Departments table that shows details of depart...,0,N
9,def,human,dept,BASE TABLE,InnoDB,10,Dynamic,4,4096,16384,...,NaN,2024-03-25 16:26:56,NaT,None,utf8mb4_general_ci,None,,,0,N
10,def,human,emp,BASE TABLE,InnoDB,10,Dynamic,14,1170,16384,...,NaN,2024-03-25 16:26:56,NaT,None,utf8mb4_general_ci,None,,,0,N
11,def,human,employees,BASE TABLE,InnoDB,10,Dynamic,107,153,16384,...,NaN,2024-03-27 16:20:22,NaT,None,utf8mb4_general_ci,None,,employees table. Contains 107 rows. References...,0,N
12,def,human,favorite_tb,BASE TABLE,InnoDB,10,Dynamic,25,655,16384,...,27.0,2024-03-27 16:20:55,NaT,None,utf8mb3_general_ci,None,,단골,0,N
13,def,human,holiday_parking,BASE TABLE,InnoDB,10,Dynamic,13740,268,3686400,...,14204.0,2024-03-26 09:45:01,NaT,None,utf8mb3_general_ci,None,,,0,N
14,def,human,job_history,BASE TABLE,InnoDB,10,Dynamic,10,1638,16384,...,11.0,2024-03-27 16:20:22,NaT,None,utf8mb4_general_ci,None,,Table that stores job history of the employees...,0,N
15,def,human,jobs,BASE TABLE,InnoDB,10,Dynamic,19,862,16384,...,NaN,2024-03-27 16:20:20,NaT,None,utf8mb4_general_ci,None,,jobs table with job titles and salary ranges. ...,0,N
16,def,human,locations,BASE TABLE,InnoDB,10,Dynamic,23,712,16384,...,NaN,2024-03-27 16:20:22,NaT,None,utf8mb4_general_ci,None,,Locations table that contains specific address...,0,N
17,def,human,nara,BASE TABLE,InnoDB,10,Dynamic,0,0,16384,...,NaN,2024-04-19 10:31:38,NaT,None,utf8mb4_general_ci,None,,,0,N
18,def,human,numbers,BASE TABLE,InnoDB,10,Dynamic,0,0,16384,...,1.0,2024-03-27 15:00:16,NaT,None,utf8mb4_general_ci,None,,,0,N
19,def,human,regions,BASE TABLE,InnoDB,10,Dynamic,4,4096,16384,...,NaN,2024-03-27 16:20:20,NaT,None,utf8mb4_general_ci,None,,,0,N
20,def,human,shop_tag_tb,BASE TABLE,InnoDB,10,Dynamic,9214,35,327680,...,27711.0,2024-03-27 16:20:55,NaT,None,utf8mb3_general_ci,None,,매장과 태그들,0,N
21,def,human,shop_tb,BASE TABLE,InnoDB,10,Dynamic,867,245,212992,...,902.0,2024-03-27 16:20:55,NaT,None,utf8mb3_general_ci,None,,매장,0,N
22,def,human,tag_tb,BASE TABLE,InnoDB,10,Dynamic,2198,59,131072,...,2199.0,2024-03-27 16:20:55,NaT,None,utf8mb3_general_ci,None,,태그,0,N
23,def,human,user_tb,BASE TABLE,InnoDB,10,Dynamic,15,1092,16384,...,24.0,2024-03-27 16:20:55,NaT,None,utf8mb3_general_ci,None,,사용자,0,N
24,def,human,visitor_tb,BASE TABLE,MyISAM,10,Dynamic,36879,31,1152444,...,36880.0,2024-03-27 10:01:59,2024-03-27 10:01:59,None,utf8mb3_general_ci,None,,방문자수,288230376151710720,N

In [137]:
dt = {'public_no':'aaaa','public_name':'dfafda','page_url':'https://'}

In [138]:
# table_name nara
# public_no, public_name, page_url, public_price,predict_price
stmt = """
create table nara(
public_no varchar(30),
public__name varchar(50),
page_url varchar(255),
public_price varchar(10),
predict_price varchar(10)
)
"""
conn.execute(text(stmt))

OperationalError: (pymysql.err.OperationalError) (1050, "Table 'nara' already exists")
[SQL:
create table nara(
public_no varchar(30),
public__name varchar(50),
page_url varchar(255),
public_price varchar(10),
predict_price varchar(10)
)
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [139]:
stmt="""
select * from information_schema.columns
where table_name = 'nara'

"""
pd.read_sql(stmt,conn)

,TABLE_CATALOG,TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,ORDINAL_POSITION,COLUMN_DEFAULT,IS_NULLABLE,DATA_TYPE,CHARACTER_MAXIMUM_LENGTH,CHARACTER_OCTET_LENGTH,...,DATETIME_PRECISION,CHARACTER_SET_NAME,COLLATION_NAME,COLUMN_TYPE,COLUMN_KEY,EXTRA,PRIVILEGES,COLUMN_COMMENT,IS_GENERATED,GENERATION_EXPRESSION
0,def,human,nara,public_no,1,NULL,YES,varchar,30,120,...,None,utf8mb4,utf8mb4_general_ci,varchar(30),,,"select,insert,update,references",,NEVER,None
1,def,human,nara,public__name,2,NULL,YES,varchar,50,200,...,None,utf8mb4,utf8mb4_general_ci,varchar(50),,,"select,insert,update,references",,NEVER,None
2,def,human,nara,page_url,3,NULL,YES,varchar,255,1020,...,None,utf8mb4,utf8mb4_general_ci,varchar(255),,,"select,insert,update,references",,NEVER,None
3,def,human,nara,public_price,4,NULL,YES,varchar,10,40,...,None,utf8mb4,utf8mb4_general_ci,varchar(10),,,"select,insert,update,references",,NEVER,None
4,def,human,nara,predict_price,5,NULL,YES,varchar,10,40,...,None,utf8mb4,utf8mb4_general_ci,varchar(10),,,"select,insert,update,references",,NEVER,None

In [140]:
{'public_no':'aaaa','public_name':'dfafda','page_url':'https://'}

{'public_no': 'aaaa', 'public_name': 'dfafda', 'page_url': 'https://'}

In [141]:
def insert_nara(dt):
    sql = "insert into nara(public_no,public_name,page_url)"
    sql += f" values('{dt['public_no']}', '{dt['public_name']}', '{dt['page_url']}')"
    conn.execute(text(sql))
    conn.execute(text('commit'))
    return pd.read_sql(f"select * from nara where public_no='{dt['public_no']}'",conn)

In [142]:
conn.close()

In [149]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\user\anaconda3\lib\site-packages (4.19.0)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\user\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (2.0.7)
Requirement already satisfied: trio~=0.17 in c:\users\user\anaconda3\lib\site-packages (from selenium) (0.25.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\user\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\user\anaconda3\lib\site-packages (from selenium) (2024.2.2)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\user\anaconda3\lib\site-packages (from selenium) (4.9.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (23.2.0)
Requirement already satisfied: sortedcontainers in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\user\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.16.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\user\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\user\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\user\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\user\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [143]:
conn = engine.connect()

In [144]:
pd.read_sql("select * from nara",conn)

Empty DataFrame
Columns: [public_no, public__name, page_url, public_price, predict_price]
Index: []

In [166]:
def update_nara(public_no,*args):
    sql = "update nara set "
    num = len(args)
    i = 1
    for col,val in args:
        if i < num:
            sql += f",{col}= '{val}', "
        else:
            sql += f",{col}= '{val}' "
        i += 1
    sql += f"where public_no = '{public_no}'"
    conn.execute(text(sql))
    conn.execute(text('commit'))
    return pd.read_sql("select * from nara,conn")

In [167]:
import pandas as pd
pd.read_sql("select * from nara",conn)

Empty DataFrame
Columns: [public_no, public__name, page_url, public_price, predict_price]
Index: []

In [168]:
update_nara('aaaa',('public_name,'나라장터'),('page_url','http://nara.org'),('predict_price','50,000'))

SyntaxError: unterminated string literal (detected at line 1) (2971108563.py, line 1)

In [148]:
def aaa(*args):
    for arg1,arg2 in args:
        print(len(args))
        print(arg1,arg2)
    return

In [129]:
aaa((1,2),(2,3))

2
1 2
2
2 3